### ISSUE TITLE
Error in code getToken

### ISSUE THREAD

**Issue by alex88** [mulesoft/js-client-oauth2#119]
I'm trying to use this library with AWS cognito and it's OAuth2 redirect flow.
After doing the redirect and receiving the callback I pass my:
```
/login?code=81fc12ff-8d62-4111-a0e7-962641361e4a
```
to `client.code.getToken(uri)` and I get this error:

```

/Users/alex/Projects/myapp/node_modules/servie/src/headers.ts:25
      this.object[key] = typeof value === "string" ? value : value.map(String);
                                                                   ^
TypeError: value.map is not a function
    at Headers.append (/Users/alex/Projects/myapp/node_modules/servie/src/headers.ts:25:68)
    at Headers.extend (/Users/alex/Projects/myapp/node_modules/servie/src/headers.ts:89:39)
    at new Headers (/Users/alex/Projects/myapp/node_modules/servie/src/headers.ts:12:20)
    at getDefaultHeaders (/Users/alex/Projects/myapp/node_modules/servie/src/node.ts:252:19)
    at new Response (/Users/alex/Projects/myapp/node_modules/servie/src/node.ts:215:21)
    at new HttpResponse (/Users/alex/Projects/myapp/node_modules/popsicle-transport-http/src/index.ts:69:5)
    at new Http2Response (/Users/alex/Projects/myapp/node_modules/popsicle-transport-http/src/index.ts:76:1)
    at ClientHttp2Stream.onResponse (/Users/alex/Projects/myapp/node_modules/popsicle-transport-http/src/index.ts:444:19)
    at Object.onceWrapper (events.js:288:20)
    at ClientHttp2Stream.emit (events.js:200:13)
```

now I don't know what calls that because `events.js` it's not a full path so I'm not able to understand the flow, but trying to log what's on that line it seems it's trying to add an header called `:status` with value `400` as number, that doesn't work because `typeof value` is `number` and not `string` so it tries to call map on a string.

I don't know if it's this library passing that value because I wasn't able to find that part of code, but adding a `typeof value === 'number'` check fixed it

**Comment by Raziel2244** [comment]
I’m facing this same issue too, going to try an earlier version in case it’s related to the popsicle version change mentioned in another issue- maybe try the last version of this?

**Comment by Raziel2244** [comment]
Installed v4.2.4 as a temporary fix and it did work :) maybe worth trying in the short term
[Issue 116](https://github.com/mulesoft/js-client-oauth2/issues/116#issue-466360795)

**Comment by alex88** [comment]
@Raziel2244 thanks downgrading to 4.2.4 worked for me as well :)

**Comment by Raziel2244** [comment]
Happy to help, hopefully the issue will be resolved but it looks like it’s just running too new JS now for us- although I am running the latest official node docker container so shouldn’t have a problem...

**Comment by nealeu** [comment]
That's correct.
In our case, we have :status=200 as the first header.

Changing the test to test for an array explicitly works as a fix:

```
    this.object[key] = !Array.isArray(value) ? value : value.map(String);
```

**Comment by nealeu** [comment]
I've dug into this and 4.2.4 -> 4.2.5 changing from popsicle 10 to 12 was a big change for a patch release!

Makes me glad I tell people to use npm ci not npm install on build servers!
