### ISSUE TITLE
Crash after getToken

### ISSUE THREAD

**Issue by WebExp0528** [mulesoft/js-client-oauth2#125]
I have used this package for Dropbox OAuth. After getting an access token, my code is crashed automatically.  I am getting the following error.

```
Type Error ---------------------------------------------
 
  TypeError: client.close is not a function
    at ClientHttp2Session.client.setTimeout (/.../node_modules/popsicle-transport-http/src/index.ts:770:45)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at ClientHttp2Session.emit (events.js:208:7)
    at emit (internal/http2/core.js:144:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              8.10.0
     Framework Version:         1.50.0
     Plugin Version:            1.3.8
     SDK Version:               2.1.0
 
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c NODE_ENV=dev SLS_DEBUG=* npx sls offline start -s dev
Directory: /o2a
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/.../yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

![image](https://user-images.githubusercontent.com/46267354/67654042-6a014200-f909-11e9-8deb-b216ea8c9b12.png)

**Comment by marrowleaves** [comment]
I can reproduce this with nodejs v8.9.2 and it works fine when I upgrade to nodejs v8.17.0. The latter has implemented [http2session.close](https://nodejs.org/docs/latest-v8.x/api/http2.html#http2_http2session_close_callback)

**Comment by Zagroda** [comment]
Hi,
I can reproduce it in v12.16.1

Is there some kind of fix?

**Comment by WebExp0528** [comment]
Thank you!

**Comment by postatum** [comment]
Hi @Zagroda.

Do you still face this issue?
If so, please provide steps to reproduce it.

**Comment by Zagroda** [comment]
Hi,
I'm sorry but I cant check. I did my own auth.

**Comment by postatum** [comment]
> Hi,
> I'm sorry but I cant check. I did my own auth.

Got it, thanks.

To everyone - feel free to reopen this issue, if it occurs again. I'm closing it for now.
