### ISSUE TITLE
ConnectionError: Unable to connect to localhost

### ISSUE THREAD

**Issue by renehauck** [mulesoft/js-client-oauth2#145]
Hi,
I wanted to implement your module in my Nodejs BE (Client Credentials Grant),
but I only get the error message 
```
UnhandledPromiseRejectionWarning: ConnectionError: Unable to connect to localhost
    at ClientRequest.onRequestError (/.../node_modules/popsicle-transport-http/src/index.ts:296:9)
    at Object.onceWrapper (events.js:281:20)
    at ClientRequest.emit (events.js:198:15)
    at Socket.socketErrorListener (_http_client.js:397:9)
    at Socket.emit (events.js:193:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
```
 when I try to request the token.
My code:
```typescript
export class OauthService {
  private Auth: ClientOAuth2;
  private options: ClientOAuth2.Options;
  constructor() {
    this.options = {
        accessTokenUri: config.isDev()
        ? config.ClientSecretDev
        : config.ClientSecretProd,
      clientId: config.ClientID,
      clientSecret: config.isDev()
        ? config.ClientSecretDev
        : config.ClientSecretProd,
    };

    this.Auth = new ClientOAuth2(this.options);
    this.getToken().then(data => console.log(data));
  }

  /**
   * get a valid bearer-token
   */
  async getToken() {
    const resp = await this.fifaAuth.credentials.getToken();
    return resp.accessToken;
  }
}

```
Am I doing something wrong? 
Thanks a lot

**Comment by renehauck** [comment]
Oh man how stupid of me, I used the wrong environment variable for the url. Sorry for the false alarm.
