### ISSUE TITLE
code.getToken with invalid client secret throws wrapped error "[object, Object]"

### ISSUE THREAD

**Issue by Metroninja** [mulesoft/js-client-oauth2#155]
I'm using this library for multiple clients currently, and ran into an interesting case that took me longer to debug due to the fact the error was obscured.  I had an invalid clientSecret for facebook and on the callback this library was throwing an error of "[object, Object]" with the stack trace of:
```
at /client-oauth2/src/client-oauth2.js:123:15)
at /client-oauth2/src/client-oauth2.js:271:21)
```
inspecting the body parameter for this libraries `getAuthError(body)` line 116 -  I was getting an interesting object type.  It looks like the error is being wrapped:
```
error [Object: null prototype] {
  code: 'MYCODE',
  state: ...
}
// followed by the ACTUAL error
error {
  error: {
    message: 'Error validating client secret.',
    type: 'OAuthException',
    code: 1,
    fbtrace_id: '...'
  }
}

```
So given an invalid secret the library was throwing the correct error, but only after throwing a 'broken' error where the body parameter ended up being the parsed url object, not an 'error'.  How can this happen?  Well facebook doesn't validate the client secret while the app is develop mode by default so that might be why this has surfed on the radar until now.  Thought I'd pass this along for those searching in the future and if someone (maybe me if I run into some free time) cut a PR to fix this.

**Comment by postatum** [comment]
Hi @Metroninja.

I appreciate the research you've made!
Can you please provide some code samples to help me reproduce the issue?

Thanks.

**Comment by Metroninja** [comment]
create a facebook app, bootstrap your library with the following config
```
const facebookConfig = {
clientId: 'YOUR_CLIENT_ID',
      authorizationUri: 'https://www.facebook.com/v7.0/dialog/oauth',
      accessTokenUri: 'https://graph.facebook.com/v7.0/oauth/access_token',
      clientSecret: 'ANYTHING-JUST-NOT-THE-CORRECT-SECRET',
      scopes: ['email'],
      redirectUri: 'YOUR_REDIRECT_URL',
    }
}
```
then create 2 routes + your library setup
```
    this.facebook = new ClientOAuth2(facebookConfig);
   router.get('/auth/facebook', (ctx, next) => {
    // kick off oauth 2 flow for google.
    const uri = this.facebook.code.getUri({ state: '' });
    ctx.redirect(uri);
   })
   .get(
        `/auth/facebook/callback`,
        async (ctx, next) => {
try {
      const fbAuth = await this.facebook.code.getToken(ctx.request.url);
     //  if client secret is invalid, it will crash above
    
    } catch (ex) {
       // examine ex.message
       }
    )


```

**Comment by postatum** [comment]
Hi @Metroninja.

Thanks for the code, but can you make the failing code a little more isolated? I'm having trouble reproducing your environment.

Thanks!
