### ISSUE TITLE
ECONNRESET after successful authentication

### ISSUE THREAD

**Issue by antonije-pavlovic** [mulesoft/js-client-oauth2#182]
Hey,

I am getting the following error when I am trying to do authentication with Microsoft.

Expected behavior:
   Create login URL, redirect the user to consent screen, accept callback from Microsoft, process callback and login user in the 
    app.

Current behavior:
   Create login URL, redirect the user to consent screen, accept callback from Microsoft, process callback and login user in the 
   app and after 2 minutes following error occurs:

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
    at internal/streams/destroy.js:44:17
    at TLSSocket.Socket._destroy (net.js:680:5)
    at TLSSocket.destroy (internal/streams/destroy.js:38:8)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:12)
    
Endpoints used for client initialization are:
Authorize: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
Token:   https://login.microsoftonline.com/common/oauth2/v2.0/token

We found out that problem is in the popsicle library, we changed request implementation in your library (src/request/index.js)
and instead of using popsicle we used node-fetch library(https://www.npmjs.com/package/node-fetch) and everything works as expected. This may be the possible solution for this problem.

**Comment by uip-robot-zz** [comment]
Git2Gus App is installed but the `.git2gus/config.json` doesn't exist.

**Comment by blakeembrey** [comment]
I was debugging this due to a link issue on `popsicle` and I believe this was fixed in April. Can you try `npm rm client-oauth2 && npm install client-oauth2` and see if that solved the problem? The root cause is that you're using an outdated dependency from `popsicle`, maybe because you installed and added it to your lock file during the timeframe with the broken release.
