### ISSUE TITLE
OAuth for a StackApps Application

### ISSUE THREAD

**Issue by raghavendracs** [mulesoft/js-client-oauth2#60]
Hi,

I am trying to use the package for authenticating using a StackApps application from my webapp.

The redirect is happening and asking for my authorization. Post that when the code.getToken(req.originalUrl) call is made I am getting an error as follows. Any help of what I might be doing wrong?

```js
             Error: [object Object]
    at getAuthError (/user_code/node_modules/client-oauth2/src/client-oauth2.js:115:15)
    at /user_code/node_modules/client-oauth2/src/client-oauth2.js:263:21
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```js

**Comment by raghavendracs** [comment]
@blakeembrey - Would you have any suggestions to my question above please?

**Comment by blakeembrey** [comment]
Can you log the error with the body property? It looks like the error isn’t following the expectation of being a string and instead returning an object. It might be in their docs too and just a matter of better handling serialisation of expected properties here.

**Comment by raghavendracs** [comment]
Just did that and I see that the details of error are as follows on a .catch with error.body logged.

error : { error: { type: 'invalid_request', message: 'client_id not provided' } } 

Not sure who the client_id is not getting passed in this case. Anything you think I might be doing wrong?

**Comment by blakeembrey** [comment]
Are you initialising or passing `clientId` as a config option? If so, there's no reason that should be happening. I would like to improve that error though, having `[object Object]` isn't useful.
